namespace AuditHistoryExtractorPro.Core.Models;

/// <summary>
/// Mapeo completo de los códigos de acción de la tabla 'audit' de Dataverse.
/// Basado en la documentación oficial de Dynamics 365 / Power Platform.
/// GetAuditActionName en AuditService cubre códigos no mapeados aquí.
/// </summary>
public enum AuditAction
{
    Unknown = 0,

    Create = 1,
    Update = 2,
    Delete = 3,
    Activate = 4,
    Deactivate = 5,
    Upsert = 6,

    Cascade = 11,
    Merge = 12,
    Assign = 13,
    Share = 14,
    Unshare = 15,
    Close = 16,
    Cancel = 17,
    Complete = 18,
    Resolve = 20,
    Reopen = 21,
    Fulfill = 22,
    Paid = 23,
    Qualify = 24,
    Disqualify = 25,
    Send = 26,
    Reject = 27,
    Approve = 28,
    Invoice = 29,
    Hold = 30,
    AddMember = 31,
    RemoveMember = 32,
    AssociateEntities = 33,
    DisassociateEntities = 34,
    AddMembers = 35,
    RemoveMembers = 36,
    AddItem = 37,
    RemoveItem = 38,
    AddSubstitute = 39,
    RemoveSubstitute = 40,
    SetState = 41,
    Renew = 42,
    Revise = 43,
    Win = 44,
    Lose = 45,
    InternalProcessing = 46,
    Reschedule = 47,
    ModifyShare = 48,
    UnshareExtended = 49,
    Book = 50,
    GenerateQuoteFromOpportunity = 51,
    AddToQueue = 52,
    AssignRoleToTeam = 53,
    RemoveRoleFromTeam = 54,
    AssignRoleToUser = 55,
    RemoveRoleFromUser = 56,
    AddPrivilegesToRole = 57,
    RemovePrivilegesFromRole = 58,
    ReplacePrivilegesInRole = 59,
    ImportMappings = 60,
    Clone = 61,
    SendDirectEmail = 62,
    OrganizationEnabled = 63,
    UserAccessViaWeb = 64,
    UserAccessViaWebServices = 65,

    // ─── Códigos de administración / auditoría de metadatos (100-113) ───────
    DeleteEntity          = 100,
    DeleteAttribute       = 101,
    AuditChangeEntityLevel = 102,
    AuditChangeAttributeLevel = 103,
    AuditChangeOrgLevel   = 104,
    EntityAuditStarted    = 105,
    AttributeAuditStarted = 106,
    AuditEnabled          = 107,
    EntityAuditStopped    = 108,
    AttributeAuditStopped = 109,
    AuditDisabled         = 110,
    AuditLogDeletion      = 111,
    UserAccessAuditStarted = 112,
    UserAccessAuditStopped = 113,

    // ─── Ciclo de vida / retención / firewall (115-120) ─────────────────────
    Archive               = 115,
    Retain                = 116,
    RollbackRetain        = 117,
    IPFirewallAccessDenied  = 118,
    IPFirewallAccessAllowed = 119,
    Restore               = 120,
}
